name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t jwsv-index-page-container:latest .

      - name: Save Docker image to tar
        run: docker save jwsv-index-page-container:latest -o jwsv-index-page-container.tar

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
    
      - name: Add SSH host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer Docker image
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key -p ${{ secrets.SSH_PORT }}" jwsv-index-page-container.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker load -i ~/jwsv-index-page-container.tar

            docker stop jwsv-index-page-container-container || true
            docker rm jwsv-index-page-container-container || true
            docker image prune -f || true

            docker run -d \
              -p 9002:80 \
              --name jwsv-index-page-container-container \
              jwsv-index-page-container:latest

            rm -f ~/jwsv-index-page-container.tar